 <nav>
     <div class="logo">
         <img src="view/img/logo.webp">
     </div>
 </nav>
 <main>
     <div class="description">
         <p>Bienvenue chez <span>Handyman</span>, votre entreprise d’homme à tout faire (Multi-services). Je propose
             à mes clients
             de la région de Cuers et ses alentours divers services adaptés en fonction de leurs besoins, et ce
             depuis notre création. Avec la garantie d'une intervention rapide, ma société réalise les petits travaux
             de bricolage que les artisans traditionnels peinent à placer entre leurs gros chantiers. je suis donc là
             pour m'assurer que mes clients obtiennent des résultats de qualité.</p>
     </div>
     <h2 id="service">mes services</h2>
     <div class="service">
         <div class="ext_pic_mobile"></div>
         <div class="ext_div left_tile">
             <div class="ext_pic">
             </div>
             <ul>
                 <h3 class="h3m">extérieur </h3>
                 <li> Graisser un volet, une porte ou une fenêtre
                 </li>
                 <li> Nettoyage de la terrasse
                 </li>
                 <li> Entretien d’espaces verts
                 </li>
                 <li> Petit élagage
                 </li>
                 <li> Tonte de haie
                 </li>
                 <li> Tonte de pelouse
                 </li>
                 <li> Petit jardinage
                 </li>
                 <li> Entretien du potager
                 </li>
                 <li> Petite maçonnerie / petit pavage
                 </li>
                 <li> Pose d’allée de jardin
                 </li>
                 <li> Etc...
                 </li>

             </ul>
         </div>
         <div class="int_pic_mobile"></div>
         <div class="int_div right_tile">
             <div class="int_pic">
             </div>
             <ul>
                 <h3 class="h3m">intérieur </h3>
                 <li>Montage de meuble en kit</li>
                 <li>Fixation de prise électrique</li>
                 <li>Graissage de porte ou de fenêtre</li>
                 <li>Purger des radiateurs</li>
                 <li>Débouchage d’évier</li>
                 <li>Pose d’un joint de douche, baignoire ou lavabo</li>
                 <li>Changement d’un fusible</li>
                 <li>Installation d’un judas de porte</li>
                 <li>Etc ...</li>
             </ul>
         </div>
     </div>
     <div class="desktop_di">
         <div class="description">
             <p class="first_part">"Mon dévouement sans faille à la réalisation de mon travail fait que mes clients
                 me connaissent pour
                 mon
                 éthique, ma ponctualité et mes services de grande qualité. Les options de personnalisation et les
                 prix
                 correspondants permettent à tous les budgets de trouver leur compte, ce qui vous permet d'avoir
                 toujours
                 une solution à portée de main".
             </p>
             <p class="second_part"> Jetez un œil à l'ensemble de <a id="serv" class="gr">mes services</a> et <a id="cont" class="gr">contactez-moi</a> dès
                 aujourd'hui.
             </p>
         </div>
         <div class="profil">
             <div class="profil_pic">
             </div>
             <div class="profil_info">
                 <p>Bonjour. Je suis Fabrice le fondateur de Handyman. Je serai la personne que vous rencontrerez si
                     vous
                     faites appel à mes services. Après avoir eu diverses expériences professionnelles et ayant
                     acquis
                     une certaine aisance, j’ai pris la décision de mettre à profit ces capacités en ouvrant mon
                     entreprise d’homme à tout faire afin d’aider les personnes qui en ont besoin et qui cherchent
                     une
                     personne de confiance.</p>
             </div>
         </div>
     </div>
     <h2>notre metier</h2>
     <div class="description work">
         <p>L'homme à tout faire est expert pour les réparations en général, c’est-à-dire des travaux de maintenance,
             de décoration et de bricolage. Où que vous soyez, vous avez des problèmes de plomberie et en même temps
             d’autres petits soucis de bricolage ? Au lieu de faire appel à un plombier, il est recommandé de
             contacter un homme à tout faire. Il peut aussi vous être utile pour des réparations mineures à
             l’intérieur et à l’extérieur de la maison, ou tout autre entretien. Il est donc idéal pour tous vos
             projets.</p>
     </div>
     <h2>tarifs</h2>
     <div class="service tiles">
         <div class="left_tile">
             <i class="fas fa-sun"></i>
             <h3>journée</h3>
             <p>40€ de l'heure Applicable en semaine du lundi au vendredi en journée (de 9H00 à 18H00), hors jours
                 fériés. Hors *frais de déplacement</p>
         </div>
         <div class="right_tile">
             <i class="fas fa-moon"></i>
             <h3>soir et week-end</h3>
             <p>45€ de l'heure Applicable en semaine après 18H, les samedis, dimanches et jours fériés. Hors *frais
                 de déplacement</p>
         </div>
     </div>
     <h2>contact</h2>
     <div class="contact_form" id="contact_form">
         <div class="mail_contact">
             <i class="far fa-envelope"></i>
             <p>contact@handyman1990.fr</p>
         </div>
         <div class="phone_contact">
             <i class="fas fa-phone-square-alt"></i><a href="tel:+33679890275">06 79 89 02 75</a>
         </div>
     </div>
     <!-- <div class="phone"><a href="tel:+33679890275"><i class="fas fa-phone"></i></a></div> -->

     <div class="tarif_condition">
         <small>Facturation à la demi-heure. *Les frais de déplacements s'élèvent à 20€, (pour tout déplacement
             au-delà de 20 km du lieu de l’entreprise (Cuers 83390) un supplément sera facturé à hauteur de 1€ par km
             parcouru). Des frais supplémentaires seront pratiqués par l’entreprise si celle-ci a recours au
             stationnement payant ou à l'évacuation de déchets, plus d'infos <a href="https://www.ecologie.gouv.fr/gestion-des-dechets-principes-generaux">ici</a>.</small>
     </div>