<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta property="og:title" content="handyman 1990">
    <meta property="og:type" content="website">
    <meta property="og:description" content="Entreprise multi services qui vous accompagne dans la réalisation de vos projets. Du jardinage au petit bricolage faites confiance a votre homme toute main.">
    <meta property="og:url" content="https://handyman1990.fr/">
    <link rel="apple-touch-icon" sizes="180x180" href="view/img/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="view/img/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="view/img/favicon/favicon-16x16.png">
    <link async rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <link rel="stylesheet" href="view/css/normalize.min.css">
    <link rel="stylesheet" href="view/css/style.css">
    <script src="view/js/jquery.js"></script>
    <title>HandyMan - Homme à tout faire à Toulon, Cuers</title>
</head>

<body>
    <main>
        <?php include $template . ".phtml"; ?>
    </main>

    <footer>
    </footer>
    <script src="view/js/script.js"></script>
    <noscript>Your browser does not support JavaScript!</noscript>
</body>

</html>